<article id="article">
  <div class="title">
    <span class="date"><?= strftime("%d %B %Y", date_timestamp_get(date_create($news['created_at']))); ?></span>
    <h1><?= htmlspecialchars($news['title']) ?></h1>
  </div>
  <div id="article-content-wrapper">
    <img
      src="assets/images/news/<?= htmlspecialchars($news['image']) ?>"
      alt="<?= htmlspecialchars($news['title']) ?>"
      title="<?= htmlspecialchars($news['title']) ?>"
     />
    <div class="content">
      <?= ($news['content']) ?>
      <?php if ($news['iframe_link'] !== null): ?>
          <iframe class="" width="560" height="315" src="<?= htmlspecialchars($news['iframe_link']) ?>" frameborder="0"
                  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; Transparency"
          />
      <?php endif ?>
    </div>
  </div>
  <div class="back-link">
    <a class="button-link" href="news.php#<?= $news['id'] ?>">Retour aux news</a>
  </div>
</article>
