<article id="article" class="news">
    <div class="title">
        <h1><?= htmlspecialchars($news['title']) ?></h1>
        <span class="date"><?= strftime("%d %B %Y", date_timestamp_get(date_create($news['created_at']))); ?></span>
    </div>
    <?php if ($news['image'] !== null): ?>
        <img src="assets/images/news/<?= htmlspecialchars($news['image']) ?>"
             alt="<?= htmlspecialchars($news['title']) ?>"
             title="<?= htmlspecialchars($news['title']) ?>">
    <?php endif ?>
    <div class="content clearFix"><?= ($news['content']) ?></div>
    <?php if ($news['iframe_link'] !== null): ?>
        <iframe class="" width="560" height="315" src="<?= htmlspecialchars($news['iframe_link']) ?>" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; Transparency"
        ></iframe>

    <?php endif ?>
    <a class="button-link" href="news.php#<?= $news['id'] ?>">Retour aux news</a>
</article>
