<section id="band">
    <article>
        <h1>THIS IS EIGHT SINS</h1>
        <ul id="members">
            <li class="member" id="jambon-text"><strong>Julien Alves</strong> - <span>Batterie</span></li>
            <li class="member" id="arno-text"><strong>Arnaud Groby</strong> - <span>Guitare</span></li>
            <li class="member" id="lox-text"><strong>Loïc Pouillon</strong> - <span>Chant</span></li>
            <li class="member" id="mike-text"><strong>Mikael Loran</strong> - <span>Basse</span></li>
        </ul>
        <ul id="members-identification">
            <li id="classic-band"><img src="assets/images/IMG_1385.jpg" alt="EIGHT SINS" title="EIGHT SINS"></li>
            <li id="glam-band" class="hide"><img src="assets/images/IMG_1384.jpg" alt="EIGHT SINS GLAM" title="EIGHT SINS GLAM"></li>
            <li><div class="member-face" id="jambon"></div></li>
            <li><div class="member-face" id="arno"></div></li>
            <li><div class="member-face" id="lox"></div></li>
            <li><div class="member-face" id="mike"></div></li>
        </ul>
    </article>
    <article id="biography">
        <h2>BEERS <span>&</span> MOSHPIT</h2>
        <p>
            Deux mots qui définissent parfaitement Eight Sins. <strong>Groupe de Thrash Hardcore</strong> fondé en 2006 par une bande
            de potes animés par la même passion et le même objectif : donner le meilleur sur scène quoiqu’il arrive.
            Grandement influencé par le <strong>Thrash américain</strong> ainsi que le <strong>New-York Hardcore</strong>, la musique d’Eight Sins est
            rapide, lourde, précise et taillée pour le live.
        </p>
        <p>
            Après plus de dix ans d’existence, cinq enregistrements studio, plusieurs clips originaux et de nombreux
            concerts en Europe, le groupe s’est forgé une solide réputation dans la <strong>scène Hardcore-Metal française</strong>.
            Ce qui lui aura notamment permis de partager l’affiche avec de grands noms comme Sepultura, Walls of
            Jericho, Agnostic Front, Terror, Municipal Waste, Madball, Sick of it All, Unearth, Black Bomb A ou encore
            Lofofora... et également de se produire au <strong>Hellfest</strong>.
        </p>
        <p>
            A chaque concert la même intensité et énergie, Eight Sins envoi son set avec rage et passion. C’est au
            moment de monter sur scène que la fête commence et personne n’en sortira indemne !!
        </p>
    </article>
</section>
