<section id="band">
  <article>
    <h1>THIS IS EIGHT SINS</h1>
    <ul id="members">
      <li class="member" id="jambon-text"><strong>Julien Alves</strong> - <span>Batterie</span></li>
      <li class="member" id="mike-text"><strong>Mikael Loran</strong> - <span>Basse</span></li>
      <li class="member" id="lox-text"><strong>Loïc Pouillon</strong> - <span>Chant</span></li>
      <li class="member" id="arno-text"><strong>Arnaud Groby</strong> - <span>Guitare</span></li>
    </ul>
    <ul id="members-identification">
      <li id="classic-band"><img src="assets/images/eightsins-2023.jpg" alt="EIGHT SINS" title="EIGHT SINS"></li>
      <li>
        <div class="member-face" id="jambon"></div>
      </li>
      <li>
        <div class="member-face" id="arno"></div>
      </li>
      <li>
        <div class="member-face" id="lox"></div>
      </li>
      <li>
        <div class="member-face" id="mike"></div>
      </li>
    </ul>
  </article>
  <article id="biography">
    <h2 class="primary-color">BEERS <span>&</span> MOSHPIT</h2>
    <p>
      Deux mots qui définissent parfaitement <strong class="primary-color">EIGHT SINS</strong>.
    </p>
    <p>
      Groupe de crossover <strong>(metal-hardcore, thrash)</strong>, fondé en 2006 par une bande de potes animés par le
      même objectif et la même passion : donner le meilleur d'eux-mêmes sur scène quoiqu’il arrive. Eight Sins est
      clairement influencé par le <strong>thrash américain</strong> ainsi que par la <strong>scène hardcore de New
        York</strong>.
    </p>
    <p>
      Leur musique est rapide, lourde, précise et taillée pour le live. Après plus de quinze ans d'existence, six
      enregistrements studio, plusieurs clips musicaux originaux et de nombreux concerts en Europe, le groupe s'est
      forgé une solide réputation dans la <strong>scène metal française</strong>.
    </p>
    <p>
      Cela leur a notamment permis de partager la scène avec de grands noms tels que Sepultura, Walls of Jericho,
      Agnostic Front, Terror, Municipal Waste, Madball, Sick of it All, Unearth, Black Bomb A ou encore Lofofora, et
      également de se produire dans les plus grands festivals français tels que le <strong>Hellfest</strong>, le
      <strong>Sylak Open Air</strong> et le Plane'r Fest.
    </p>
    <p>
      Eight Sins a sorti son premier album en 2008, intitulé "Straight Hate", suivi un an plus tard d'un EP en
      collaboration avec le rappeur français VII, intitulé "Blood Of Revenge".
    </p>
    <p>
      En 2013, le groupe a rejoint le label suisse Bad Mood Records dans le but de donner naissance à son deuxième
      album, intitulé "World Of Sorrow", suivi trois ans plus tard de "SERPENTS" (2016, Thousand Ghosts Highway
      Records).
    </p>
    <p>
      En 2023, Eight Sins sortira son quatrième album, intitulé "STRAIGHT TO NAMEK".
    </p>
  </article>
</section>
