<section id="contact">
  <h1>CONTACT</h1>
  <div class="information-wrapper">
    <article>
      <h3 class="primary-color">Booking</h3>
      <div class="information">
        <span>Arnaud</span>
        <div>06 31 80 23 42 / <a href="mailto:eightsinshxc@gmail.com">eightsinshxc@gmail.com</a></div>
      </div>
    </article>
  </div>
  <article>
    <h3 class="primary-color">Support</h3>
    <ul>
      <li>
        <a href="https://www.facebook.com/Vvisionagency/" target="_blank">
          <img src="assets/images/logos/victory-vision.png" alt="Victory Vision Agency" title="Victory Vision Agency" width="100">
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/warmaudio.decines/" target="_blank">
          <img src="assets/images/logos/warmaudio.png" alt="Warmaudio" title="Warmaudio" width="100">
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/tghasso/" target="_blank">
          <img src="assets/images/logos/tgh.jpg" alt="Thousand Ghosts Highway" title="Thousand Ghosts Highway"
               width="100">
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/badmoodrecords/" target="_blank">
          <img src="assets/images/logos/badmood.jpg" alt="Badmood Records" title="Badmood Records" width="100">
        </a>
      </li>
    </ul>
  </article>
  <article>
    <h3 class="primary-color">Sponso</h3>
    <ul>
      <li>
        <a href="https://creveclothing.com/" target="_blank">
          <img src="assets/images/logos/creve.jpeg" alt="Crève Clothing" title="Crève Clothing" width="100">
        </a></li>
      <li>
        <a href="https://trxcymbals.com/" target="_blank">
          <img src="assets/images/logos/trxcymbals.jpg" alt="TRX Cymbals" title="TRX Cymbals" width="100">
        </a>
      </li>
      <li>
        <a href="https://www.espguitars.com/" target="_blank">
          <img src="assets/images/logos/esp-ltd.png" alt="ESP LTD guitars" title="ESP LTD guitars" width="100">
        </a>
      </li>
      <li>
        <a href="https://www.shure.com/" target="_blank">
          <img src="assets/images/logos/shure.png" alt="Shure" title="Shure" width="100">
        </a>
      </li>
      <li>
        <a href="https://sennheiser.com/" target="_blank">
          <img src="assets/images/logos/sennheiser.png" alt="Sennheiser" title="Sennheiser" width="100">
        </a>
      </li>
    </ul>
  </article>
</section>
