<section id="contact">
  <h1>CONTACTS</h1>
  <div class="information-wrapper">
    <article class="booking">
      <h3>Booking</h3>
      <div class="information">
        <a href="mailto:ello@epic-tour.com">Elodie T-G</a>
        <div>06 46 12 21 84</div>
      </div>
      <div class="information">
        <a href="mailto:elodie.psrl@epic-tour.com">Elodie Psrl</a>
        <div>06 28 71 93 84</div>
      </div>
    </article>
    <article>
      <h3>Band</h3>
      <div>eightsinshxc[at]gmail.com</div>
    </article>
  </div>
  <article>
    <h3>Support</h3>
    <ul>
      <li>
        <a href="https://www.epic-tour.com/nos-artistes-1/artistes-france/eight-sins/">
          <img src="assets/images/logos/epic-tour.png" alt="Epic Tour Booking" title="Epic Tour Booking" width="100">
        </a>
      </li>
      <li>
        <a href="https://creveclothing.com/">
          <img src="assets/images/logos/creve.jpeg" alt="Crève Clothing" title="Crève Clothing" width="100">
        </a></li>
      <li>
        <a href="https://trxcymbals.com/">
          <img src="assets/images/logos/trxcymbals.jpg" alt="TRX Cymbals" title="TRX Cymbals" width="100">
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/warmaudio.decines/">
          <img src="assets/images/logos/warmaudio.png" alt="Warmaudio" title="Warmaudio" width="100">
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/tghasso/">
          <img src="assets/images/logos/tgh.jpg" alt="Thousand Ghosts Highway" title="Thousand Ghosts Highway"
               width="100">
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/badmoodrecords/">
          <img src="assets/images/logos/badmood.jpg" alt="Badmood Records" title="Badmood Records" width="100">
        </a>
      </li>
    </ul>
  </article>
</section>
