<section id="contact">
    <h1>Contact</h1>
    <div>
        <article>
            <h3>Booking</h3>
            <p>eightsinshxc[at]gmail.com</p>
        </article>
        <article>
            <h3>Publishing</h3>
            <p><span>KNT Publishing :</span> contact[at]knt.fr</p>
        </article>
    </div>
    <article>
        <h3>Support</h3>
        <ul>
            <li class="animate"><a href="https://trxcymbals.com/"><img src="assets/images/logos/trxcymbals.jpg" alt="TRX Cymbals" title="TRX Cymbals" width="100"></a></li>
            <li class="animate"><a href="https://knt.fr/"><img src="assets/images/logos/knt.png" alt="KNT Publishing" title="KNT Publishing" width="100"></a></li>
            <li class="animate"><a href="https://www.facebook.com/warmaudio.decines/"><img src="assets/images/logos/warmaudio.png" alt="Warmaudio" title="Warmaudio" width="100"></a></li>
            <li class="animate"><a href="https://www.facebook.com/tghasso/"><img src="assets/images/logos/tgh.jpg" alt="Thousand Ghosts Highway" title="Thousand Ghosts Highway" width="100"></a></li>
            <li class="animate"><a href="https://www.facebook.com/badmoodrecords/"><img src="assets/images/logos/badmood.jpg" alt="Badmood Records" title="Badmood Records" width="100"></a></li>
        </ul>
    </article>
</section>
