<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title><?= $pageTitle ?></title>
  <meta name="description" content="<?= $metaDescription ?>">
  <meta name="keywords" content="<?= $metaKeywords ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="canonical" href="<?= $canonicalUrl ?>">
  <!--Favicons-->
  <link rel="apple-touch-icon" sizes="180x180" href="assets/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon/favicon-16x16.png">
  <link rel="manifest" href="assets/favicon/site.webmanifest?v=8jMYrOngOg">
  <link rel="mask-icon" href="assets/favicon/safari-pinned-tab.svg" color="#5bbad5">
  <link rel="shortcut icon" href="assets/favicon/favicon.ico?v=8jMYrOngOg">
  <meta name="apple-mobile-web-app-title" content="Eight Sins">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="application-name" content="Eight Sins">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#000000">
  <!--Open Graph -->
  <meta property="og:url" content="https://www.eightsins.fr">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Eight Sins Official Website">
  <meta property="og:description"
        content="Thrash Metal Hardcore band from France (Grenoble). Tour dates, last news, music, videos here !!"/>
  <meta property="og:image" content="https://www.eightsins.fr/assets/images/8sinsbackground.jpg">
  <!--Fonts & CSS -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
  <?php if (getenv('ENV') === 'dev'): ?>
    <link rel="stylesheet" href="../src/css/normalize.css">
    <link rel="stylesheet" href="../src/css/variables.css">
    <link rel="stylesheet" href="../src/css/global-settings.css">
    <link rel="stylesheet" href="../src/css/animations.css">
    <link rel="stylesheet" href="../src/css/burgermenu.css">
    <link rel="stylesheet" href="../src/css/main-content.css">
    <link rel="stylesheet" href="../src/css/footer.css">
  <?php else: ?>
    <link rel="stylesheet" href="assets/css/main.min.css">
  <?php endif ?>
  <?php if ($template === 'welcome'): ?>
    <?= '<link rel="stylesheet" href="assets/css/welcome-page.css">' ?>
  <?php endif ?>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-0T89NZHR69"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-0T89NZHR69');
  </script>
</head>
<body>
<header>
  <nav id="main-nav">
    <ul class="nav-header">
      <li id="burger-button">
        <div class="burger-menu-icon top-line"></div>
        <div class="burger-menu-icon middle-line"></div>
        <div class="burger-menu-icon bottom-line"></div>
      </li>
      <li id="main-logo">
        <a href="index.php"><img src="assets/images/logo2023jauneHD.png" alt="EIGHT SINS" title="EIGHT SINS"></a>
      </li>
      <li class="menu-list">
        <ul>
          <li class="menu-link"><a href="index.php">WELCOME</a></li>
          <li class="menu-link"><a href="news.php">NEWS</a></li>
          <li class="menu-link"><a href="band.php">BAND</a></li>
          <li class="menu-link"><a href="tour.php">TOUR</a></li>
          <li class="menu-link"><a href="music.php">MUSIC</a></li>
          <li class="menu-link"><a href="video.php">VIDEO</a></li>
          <li class="menu-link"><a href="merch.php">MERCH</a></li>
          <li class="menu-link"><a href="contact.php">CONTACT</a></li>
        </ul>
      </li>
    </ul>
  </nav>
</header>
<main id="main-wrapper">
  <div id="content-wrapper">
    <?php include "$template.phtml" ?>
  </div>
  <div id="scroll-to-top-button"><i class="fas fa-arrow-up"></i></div>
</main>
<footer>
  <nav class="social-nav">
    <a href="https://facebook.com/eightsins" target="_blank" rel="noopener">
      <i class="fa-brands fa-facebook font-icon"></i>
    </a>
    <a href="https://instagram.com/eightsinsband" target="_blank" rel="noopener">
      <i class="fa-brands fa-instagram font-icon"></i>
    </a>
    <a href="https://open.spotify.com/artist/5M7auDu0v1IOATDBxQVfIM" target="_blank" rel="noopener">
      <i class="fa-brands fa-spotify font-icon"></i>
    </a>
    <a href="https://www.youtube.com/channel/UCqKTbXI3Ycq9Ij-bKVi7tRQ" target="_blank" rel="noopener">
      <i class="fa-brands fa-youtube font-icon"></i>
    </a>
    <a href="https://eightsins.bandcamp.com" target="_blank" rel="noopener">
      <i class="fa-brands fa-bandcamp font-icon"></i>
    </a>
  </nav>
  <p class="credits">Eight Sins <?= date_format(date_create('now'), 'Y') ?> © - All Rights Reserved.</p>
</footer>
<?php if (getenv('ENV') === 'dev'): ?>
  <script src="../src/js/utilities.js"></script>
  <script src="../src/js/Classes/DiscographyInformations.js"></script>
  <script src="../src/js/Classes/BurgerMenu.js"></script>
  <script src="../src/js/Classes/MembersIdentificator.js"></script>
  <script src="../src/js/main.js"></script>
<?php else: ?>
  <script src="assets/js/main.min.js"></script>
<?php endif ?>
<script src="https://kit.fontawesome.com/c2029d4d27.js" crossorigin="anonymous"></script>
</body>
</html>
