<article>
    <h1>EIGHT SINS DISCOGRAPHY</h1>
    <section id="disco">
        <article class="album">
            <h3>IT'S A TRAP<span class="year"> - 2018</span></h3>
            <div class="cover">
                <img class="animate" src="assets/images/disco/itsatrap.jpg" alt="It's a Trap cover"
                     title="It's a Trap cover">
                <span class="animate info-click">Cliquer pour plus d'informations</span>
                <aside class="record-info">
                    <div class="container">
                        <img src="assets/images/disco/itsatrap.jpg" alt="It's a Trap cover" title="It's a Trap cover">
                        <ul>
                            <li><h2>IT'S A TRAP</h2></li>
                            <li><span>Sortie : </span>22 Juin 2018</li>
                            <li><span>Format : </span>EP 4 titres</li>
                            <li><span>Supports : </span>Vinyl série limitée numérotée - CD - Digital</li>
                            <li><span>Production : </span>Record, Mix et Master <a
                                        href="https://www.facebook.com/warmaudio.decines/">@Warmaudio
                                    (Lyon)</a> par Mickael Kassapian
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            <iframe style="border: 0; width: 100%; height: 274px;"
                    src="https://bandcamp.com/EmbeddedPlayer/album=1362976134/size=large/bgcol=333333/linkcol=9c2685/artwork=none/transparent=true/"
                    seamless><a href="http://eightsins.bandcamp.com/album/its-a-trap">It&#39;s a Trap by EIGHT
                    SINS</a>
            </iframe>
        </article>
        <article class="album">
            <h3>SERPENTS<span class="year"> - 2016</span></h3>
            <div class="cover">
                <img class="animate" src="assets/images/disco/serpents.jpg" alt="Serpents cover" title="Serpents cover">
                <span class="animate info-click">Cliquer pour plus d'informations</span>
                <aside class="record-info">
                    <div class="container">
                        <img src="assets/images/disco/serpents.jpg" alt="Serpents cover" title="Serpents cover">
                        <ul>
                            <li><h2>SERPENTS</h2></li>
                            <li><span>Sortie : </span>21 Novembre 2016</li>
                            <li><span>Format : </span>Album 10 titres</li>
                            <li><span>Supports : </span>Digipack - Digital</li>
                            <li><span>Production : </span>Record, Mix et Master <a
                                        href="https://www.facebook.com/warmaudio.decines/">@Warmaudio
                                    (Lyon)</a> par Mickael Kassapian
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            <iframe style="border: 0; width: 100%; height: 274px;"
                    src="https://bandcamp.com/EmbeddedPlayer/album=10955803/size=large/bgcol=333333/linkcol=9d1d21/artwork=none/transparent=true/"
                    seamless><a href="http://eightsins.bandcamp.com/album/serpents">Serpents by EIGHT SINS</a>
            </iframe>
        </article>
        <article class="album">
            <h3>WORLD OF SORROW <span class="year"> - 2013</span></h3>
            <div class="cover">
                <img class="animate" src="assets/images/disco/world.jpg" alt="World of Sorrow Cover"
                     title="World of Sorrow Cover">
                <span class="animate info-click">Cliquer pour plus d'informations</span>
                <aside class="record-info">
                    <div class="container">
                        <img src="assets/images/disco/world.jpg" alt="World of Sorrow cover" title="World of Sorrow cover">
                        <ul>
                            <li><h2>WORLD OF SORROW</h2></li>
                            <li><span>Sortie : </span>10 Avril 2013</li>
                            <li><span>Format : </span>Album 9 titres</li>
                            <li><span>Supports : </span>Digipack - Digital</li>
                            <li><span>Production : </span>
                                Record & Mix <a href="https://www.facebook.com/1936-studio-255713714501262/"
                                >
                                    @1936 Studio (Paris)</a> par Antonin Chardonnereau<br>
                                Master <a href="https://www.westwestsidemusic.com/">@West West Side
                                    Music
                                    (New York City)</a> par Alan Douches
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            <iframe style="border: 0; width: 100%; height: 274px;"
                    src="https://bandcamp.com/EmbeddedPlayer/album=1584887946/size=large/bgcol=333333/linkcol=4b7c90/artwork=none/transparent=true/"
                    seamless><a href="http://eightsins.bandcamp.com/album/world-of-sorrow">World of Sorrow by EIGHT
                    SINS</a>
            </iframe>
        </article>
        <article class="album">
            <h3>BLOOD OF REVENGE<span class="year"> - 2009</span></h3>
            <div class="cover">
                <img class="animate" src="assets/images/disco/blood.png" alt="Blood of Revenge Cover"
                     title="Blood of Revenge Cover">
                <span class="animate info-click">Cliquer pour plus d'informations</span>
                <aside class="record-info">
                    <div class="container">
                        <img src="assets/images/disco/blood.png" alt="Blood of Revenge cover" title="Blood of Revenge cover">
                        <ul>
                            <li><h2>BLOOD OF REVENGE</h2></li>
                            <li><span>Sortie : </span>2 Septembre 2009</li>
                            <li><span>Format : </span>Split CD 6 titres</li>
                            <li><span>Support : </span>CD</li>
                            <li><span>Production : </span>Record, Mix et Master @Sonic Box Studio (Lyon)</li>
                        </ul>
                    </div>
                </aside>
            </div>
            <iframe style="border: 0; width: 100%; height: 274px;"
                    src="https://bandcamp.com/EmbeddedPlayer/album=1694260231/size=large/bgcol=333333/linkcol=a51d20/artwork=none/transparent=true/"
                    seamless><a href="http://eightsins.bandcamp.com/album/blood-of-revenge">Blood of Revenge by EIGHT
                    SINS</a>
            </iframe>
        </article>
        <article class="album">
            <h3>STRAIGHT HATE<span class="year"> - 2008</span></h3>
            <div class="cover">
                <img class="animate" src="assets/images/disco/straighthate.jpg" alt="Straight Hate Cover"
                     title="Straight Hate Cover">
                <span class="animate info-click">Cliquer pour plus d'informations</span>
                <aside class="record-info">
                    <div class="container">
                        <img src="assets/images/disco/straighthate.jpg" alt="Straight Hate cover" title="Straight Cover cover">
                        <ul>
                            <li><h2>STRAIGHT HATE</h2></li>
                            <li><span>Sortie : </span>10 Octobre 2008</li>
                            <li><span>Format : </span>Album 7 titres</li>
                            <li><span>Support : </span>CD</li>
                            <li><span>Production : </span>Record, Mix et Master @Sonic Box Studio (Lyon)</li>
                        </ul>
                    </div>
                </aside>
            </div>
            <iframe style="border: 0; width: 100%; height: 274px;"
                    src="https://bandcamp.com/EmbeddedPlayer/album=1224299577/size=large/bgcol=333333/linkcol=ffffff/artwork=none/transparent=true/"
                    seamless><a href="http://eightsins.bandcamp.com/album/straight-hate">Straight Hate by EIGHT SINS</a>
            </iframe>
        </article>
    </section>
</article>
