<article>
  <h1>DISCOGRAPHY</h1>
  <section id="disco"><article class="album">
      <h3>STRAIGHT TO NAMEK<span class="year"> - 2023</span></h3>
      <iframe style="border: 1px solid #ffffff73; width: 380px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=575963018/size=large/bgcol=333333/linkcol=FBE42E/transparent=true/" seamless><a href="https://eightsins.bandcamp.com/album/straight-to-namek-3">Straight To Namek by EIGHT SINS</a></iframe>
    </article>
    <article class="album">
      <h3>IT'S A TRAP<span class="year"> - 2018</span></h3>
      <iframe style="border: 1px solid #ffffff73; width: 380px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=1362976134/size=large/bgcol=333333/linkcol=cf31b0/transparent=true/" seamless><a href="https://eightsins.bandcamp.com/album/its-a-trap">It&#39;s a Trap by EIGHT SINS</a></iframe>
    </article>
    <article class="album">
      <h3>SERPENTS<span class="year"> - 2016</span></h3>
      <iframe style="border: 1px solid #ffffff73; width: 380px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=10955803/size=large/bgcol=333333/linkcol=9d1d21/transparent=true/" seamless><a href="https://eightsins.bandcamp.com/album/serpents">Serpents by EIGHT SINS</a></iframe>
    </article>
    <article class="album">
      <h3>WORLD OF SORROW <span class="year"> - 2013</span></h3>
      <iframe style="border: 1px solid #ffffff73; width: 380px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=1584887946/size=large/bgcol=333333/linkcol=4b7c90/transparent=true/" seamless><a href="https://eightsins.bandcamp.com/album/world-of-sorrow">World of Sorrow by EIGHT SINS</a></iframe>
    </article>
    <article class="album">
      <h3>BLOOD OF REVENGE<span class="year"> - 2009</span></h3>
      <iframe style="border: 1px solid #ffffff73; width: 380px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=1694260231/size=large/bgcol=333333/linkcol=a51d20/transparent=true/" seamless><a href="https://eightsins.bandcamp.com/album/blood-of-revenge">Blood of Revenge by EIGHT SINS</a></iframe>
    </article>
    <article class="album">
      <h3>STRAIGHT HATE<span class="year"> - 2008</span></h3>
      <iframe style="border: 1px solid #ffffff73; width: 380px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=1224299577/size=large/bgcol=333333/linkcol=ffffff/transparent=true/" seamless><a href="https://eightsins.bandcamp.com/album/straight-hate">Straight Hate by EIGHT SINS</a></iframe>
    </article>
  </section>
</article>
