<section id="video">
  <h1>OFFICIAL MUSIC VIDEOS</h1>
  <span>Directed by: <a href="http://www.magalilaroche.fr/" class="underlined-link"><strong>Magali Laroche</strong></a></span>
  <div class="wrapper">
    <article class="clip">
      <h3>ACID HOLE <span> - 2023</span></h3>
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/TOSy15qzVJo"
                frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
      </div>
    </article>
    <article class="clip">
      <h3>FACEPLANT <span> - 2018</span></h3>
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/QH044dU1gaE"
                frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
      </div>
    </article>
    <article class="clip">
      <h3>BEERS & MOSHPIT <span> - 2017</span></h3>
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/dVBwICNo1pk" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
      </div>
    </article>
    <article class="clip">
      <h3>TEN YEARS <span> - 2016</span></h3>
      <div class="video-container">
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/BCUCnCMeHt4"
                frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
      </div>
    </article>
  </div>
</section>
