<section id="video">
    <h1>EIGHT SINS OFFICIAL VIDEOS & CLIP</h1>
    <span>Directed by: <a href="http://www.magalilaroche.fr/"><strong>Magali Laroche</strong></a></span>
    <div class="wrapper">
        <article class="clip">
            <h3>FACEPLANT</h3>
            <div class="video-container">
                <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/QH044dU1gaE"
                        frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
            </div>
        </article>
        <article class="clip">
            <h3>TEN YEARS</h3>
            <div class="video-container">
                <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/BCUCnCMeHt4"
                        frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
            </div>
        </article>
        <article class="clip">
            <h3>BEERS & MOSHPIT</h3>
            <div class="video-container">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/dVBwICNo1pk" frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
            </div>
        </article>
    </div>
</section>
